require("overrides.5dim")
require("overrides.adv-weap")
require("overrides.ammo")

require("overrides.bobs")
require("overrides.cat")
require("overrides.color")
require("overrides.entity")
require("overrides.forcefield")
require("overrides.furnace")
require("overrides.item")
require("overrides.recipe")
require("overrides.tech")
require("overrides.science")
require("overrides.robominer")

require("prototypes.hardcrafting")
require("prototypes.chemplant")
require("prototypes.oil")
require("prototypes.nuclear")
