script.on_init(function()
      remote.call("af","setItemArray","ammo-ac",{"autocannon-shell","cannon-shell"})
      remote.call("af","addToDefaultSets","adv-ammo-turret",{group="turrets", limits= {10}, "ammo-bullets"})
      remote.call("af","addToDefaultSets","sniper-ammo-turret",{group="turrets", limits= {10}, "ammo-bullets"})
      remote.call("af","addToDefaultSets","ac-ammo-turret",{group="turrets", limits= {10}, "ammo-ac"})
      remote.call("af","addToDefaultSets","rocket-ammo-turret",{group="turrets", limits= {10}, "ammo-rockets"})
      
end)

script.on_load(function()
      remote.call("af","setItemArray","ammo-ac",{"autocannon-shell","cannon-shell"})
      remote.call("af","addToDefaultSets","adv-ammo-turret",{group="turrets", limits= {10}, "ammo-bullets"})
      remote.call("af","addToDefaultSets","sniper-ammo-turret",{group="turrets", limits= {10}, "ammo-bullets"})
      remote.call("af","addToDefaultSets","ac-ammo-turret",{group="turrets", limits= {10}, "ammo-ac"})
      remote.call("af","addToDefaultSets","rocket-ammo-turret",{group="turrets", limits= {10}, "ammo-rockets"})
end)